run2.1A: task2.1A.cpp
	gcc task2.1A.cpp -o task2.1A -l pcap
	chmod +x task2.1A
	sudo ./task2.1A

run2.1B: task2.1B.cpp
	gcc task2.1B.cpp -o task2.1B -l pcap
	chmod +x task2.1B
	sudo ./task2.1B

run2.1C: task2.1C.cpp
	gcc task2.1C.cpp -o task2.1C -l pcap
	chmod +x task2.1C
	sudo ./task2.1C

run2.2A: ./spoofing/task2.2A.c
	gcc ./spoofing/task2.2A.c -o ./spoofing/task2.2A
	chmod +x ./spoofing/task2.2A
	sudo ./spoofing/task2.2A

run2.2B: ./spoofing/task2.2B.c
	gcc ./spoofing/task2.2B.c -o ./spoofing/task2.2B
	chmod +x ./spoofing/task2.2B
	sudo ./spoofing/task2.2B

run2.3: ./spoofing/task2.3.c
	gcc ./spoofing/task2.3.c -o ./spoofing/task2.3 -l pcap
	chmod +x ./spoofing/task2.3
	sudo ./spoofing/task2.3